baseURL = 'https://lamasa02-sudo.github.io/project-practice/'
languageCode = 'ru-ru'
title = 'Dark Machine'
theme = 'minimal-black'

# Эти строки оставь - они помогают с путями
relativeURLs = true
canonifyURLs = true

[params]
  description = 'Пиксельная метроидвания'
  accentColor = '#dc2626'

[[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Журнал"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "О проекте"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Участники"
  url = "/team/"
  weight = 4

[[menu.main]]
  name = "Ресурсы"
  url = "/resources/"
  weight = 5

[markup.goldmark.renderer]
  unsafe = true